insert into library_book(category, title, author, year, press, price, total, stock) values('CS','Database System Concepts','Abraham',2011,'McGrawHill',99.00,5,4);
insert into library_book(category, title, author, year, press, price, total, stock) values('CS','Modern Operating System','Andrew',2009,'Pearson',75.00,3,1);
insert into library_book(category, title, author, year, press, price, total, stock) values('CS','Computer Network','Tanenbaum',2000,'Pearson',58.00,4,3);
insert into library_book(category, title, author, year, press, price, total, stock) values('Science','A Brief History of Time','Hawking',1996,'Bantam',255.00,5,2);
insert into library_book(category, title, author, year, press, price, total, stock) values('Fiction','Harry Potter','J.K',2008,'Bloomsbury',328.00,6,3);
insert into library_book(category, title, author, year, press, price, total, stock) values('Fiction','The Kite Runner','Khaled Hosseini',2013,'Penguin',27.00,3,2);
insert into library_book(category, title, author, year, press, price, total, stock) values('Art','Monet or the Triumph of Impressionism','Wildenstein',2010,'Taschen',165.00,2,0);
insert into library_book(category, title, author, year, press, price, total, stock) values('Art','Secret Garden','Johanna',2013,'Laurence',28.00,3,3);
insert into library_book(category, title, author, year, press, price, total, stock) values('Food','The wine Bible','Karen',2004,'Workman',128.00,5,4);
insert into library_book(category, title, author, year, press, price, total, stock) values('Food','China: The Cookbook','Chan',2016,'Phaidon',269.00,4,2);
